import type { CourseShell } from './types';

// Raw course data without lectures and sections. IDs will be generated by Supabase.
export const COURSES_DATA: CourseShell[] = [
  {
    nameAr: 'مقدمة في علوم الحاسب',
    nameEn: 'Introduction to Computer Science',
    doctor: 'د. تامر الغزالي',
    taName: 'م. أحمد علي',
    lectureDay: 'الأحد',
    sectionDay: 'الثلاثاء',
  },
  {
    nameAr: 'اساسيات برمجة حاسبات 1',
    nameEn: 'Fundamentals of Computer Programming 1',
    doctor: 'د. محمد الرملي',
    lectureDay: 'الاثنين',
    sectionDay: 'الأربعاء',
  },
  {
    nameAr: 'رياضيات 1',
    nameEn: 'Mathematics 1',
    doctor: 'د. فتحي',
    lectureDay: 'السبت',
  },
  {
    nameAr: 'فيزياء',
    nameEn: 'Physics',
    doctor: 'د. سامح السقا',
    lectureDay: 'الثلاثاء',
  },
  {
    nameAr: 'حقوق إنسان',
    nameEn: 'Human Rights',
    doctor: 'د. مجدي شرف',
    lectureDay: 'الأحد',
  },
  {
    nameAr: 'لغة انجليزية 1',
    nameEn: 'English Language 1',
    doctor: 'د. وليد سعد',
    lectureDay: 'الخميس',
  },
];